### ISSUE TITLE
[Bug] panic when using audit webhook

### ISSUE THREAD

**Issue by haupv1m** [flipt-io/flipt#3283]
### Bug Description

Got panic when using flipt with audit webhook is configured. This cause server unavailable and audit function does not work properly

### Version Info

v1.46.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Config follow https://github.com/flipt-io/flipt/blob/v1.46.0/examples/audit/webhook/docker-compose.yml
When create flag via UI, got below panic and process is not reachable anymore

```
webhook-flipt-1    | panic: invalid logger type passed, must be Logger or LeveledLogger, was *zap.Logger
webhook-flipt-1    | 
webhook-flipt-1    | goroutine 135 [running]:
webhook-flipt-1    | github.com/hashicorp/go-retryablehttp.(*Client).logger.func1()
webhook-flipt-1    | 	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:463 +0xcd
webhook-flipt-1    | sync.(*Once).doSlow(0x487c40?, 0xc0000f33f0?)
webhook-flipt-1    | 	sync/once.go:74 +0xc2
webhook-flipt-1    | sync.(*Once).Do(...)
webhook-flipt-1    | 	sync/once.go:65
webhook-flipt-1    | github.com/hashicorp/go-retryablehttp.(*Client).logger(0xc0000f3380)
webhook-flipt-1    | 	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:453 +0x45
webhook-flipt-1    | github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0000f3380, 0xc000acea08)
webhook-flipt-1    | 	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:656 +0x9b
webhook-flipt-1    | go.flipt.io/flipt/internal/server/audit/webhook.(*webhookClient).SendAudit(0xc0008c4ff0, {0x3b16400, 0xc000372e70}, {{0x304c485, 0x3}, {0x304cd89, 0x4}, {0x305204e, 0x7}, {0xc0008b6730}, ...})
webhook-flipt-1    | 	go.flipt.io/flipt/internal/server/audit/webhook/client.go:72 +0x32f
webhook-flipt-1    | go.flipt.io/flipt/internal/server/audit/webhook.(*Sink).SendAudits(0xc000b32fd8, {0x3b16400, 0xc000372e70}, {0xc000372f50?, 0x2?, 0x2?})
webhook-flipt-1    | 	go.flipt.io/flipt/internal/server/audit/webhook/webhook.go:31 +0x119
webhook-flipt-1    | go.flipt.io/flipt/internal/server/audit.(*SinkSpanExporter).SendAudits(0xc0008d4d40, {0x3b16400, 0xc000372e70}, {0xc000372f50, 0x1, 0x1})
webhook-flipt-1    | 	go.flipt.io/flipt/internal/server/audit/audit.go:85 +0x2e9
webhook-flipt-1    | go.flipt.io/flipt/internal/server/audit.(*SinkSpanExporter).ExportSpans(0xc0008d4d40, {0x3b16400, 0xc000372e70}, {0xc0008d4d60?, 0xc000b2bef2?, 0xc0009c2540?})
webhook-flipt-1    | 	go.flipt.io/flipt/internal/server/audit/audit.go:60 +0xd9
webhook-flipt-1    | go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc0006f61e0, {0x3b16390, 0xc000858140})
webhook-flipt-1    | 	go.opentelemetry.io/otel/sdk@v1.27.0/trace/batch_span_processor.go:277 +0x238
webhook-flipt-1    | go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc0006f61e0)
webhook-flipt-1    | 	go.opentelemetry.io/otel/sdk@v1.27.0/trace/batch_span_processor.go:321 +0x308
webhook-flipt-1    | go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
webhook-flipt-1    | 	go.opentelemetry.io/otel/sdk@v1.27.0/trace/batch_span_processor.go:117 +0x54
webhook-flipt-1    | created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor in goroutine 1
webhook-flipt-1    | 	go.opentelemetry.io/otel/sdk@v1.27.0/trace/batch_span_processor.go:115 +0x2e5
```

### Expected Behavior

Webhook should be fired and server still be healthy

### Additional Context

Docker

**Comment by markphelps** [comment]
Sorry about this @haupv1m !

I have a PR up for a fix. Will create a bugfix release (1.46.1) once merged.

Will also likely backport it to the `1.45.x` release branch as well since it was introduced there I believe

**Comment by markphelps** [comment]
@haupv1m this should now be fixed in the latest release: https://github.com/flipt-io/flipt/releases/tag/v1.46.1

thank you for reporting!

**Comment by alucarddelta** [comment]
This appears to have resurfaced in `1.48.0`
"docker.flipt.io/flipt/flipt:latest"

```
panic: invalid logger type passed, must be Logger or LeveledLogger, was *zap.Logger
goroutine 74 [running]:
github.com/hashicorp/go-retryablehttp.(*Client).logger.func1()
	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:463 +0xcd
sync.(*Once).doSlow(0x487c40?, 0xc0006f6b70?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
github.com/hashicorp/go-retryablehttp.(*Client).logger(0xc0006f6b00)
	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:453 +0x45
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0006f6b00, 0xc000926738)
	github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:656 +0x9b
go.flipt.io/flipt/internal/server/audit/template.(*webhookTemplate).Execute(0xc000a77410, {0x3ed7c60, 0xc000310150}, {{0x33aae34, 0x3}, {0x33ab70e, 0x4}, {0x33b1114, 0x7}, {0xc0009caaa0}, ...})
	go.flipt.io/flipt/internal/server/audit/template/executer.go:96 +0x4b2
go.flipt.io/flipt/internal/server/audit/template.(*Sink).SendAudits(0xc000d124c0, {0x3ed7c60, 0xc000310150}, {0xc000310380?, 0x2?, 0x2?})
	go.flipt.io/flipt/internal/server/audit/template/template.go:46 +0x155
go.flipt.io/flipt/internal/server/audit.(*SinkSpanExporter).SendAudits(0xc000d12500, {0x3ed7c60, 0xc000310150}, {0xc000310380, 0x1, 0x1})
	go.flipt.io/flipt/internal/server/audit/audit.go:85 +0x2e9
go.flipt.io/flipt/internal/server/audit.(*SinkSpanExporter).ExportSpans(0xc000d12500, {0x3ed7c60, 0xc000310150}, {0xc000d12520?, 0xc0000a8ef2?, 0xc000bb21c0?})
	go.flipt.io/flipt/internal/server/audit/audit.go:60 +0xd9
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc000be0140, {0x3ed7bf0, 0xc000b92050})
	go.opentelemetry.io/otel/sdk@v1.28.0/trace/batch_span_processor.go:277 +0x238
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc000be0140)
	go.opentelemetry.io/otel/sdk@v1.28.0/trace/batch_span_processor.go:321 +0x308
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
	go.opentelemetry.io/otel/sdk@v1.28.0/trace/batch_span_processor.go:117 +0x54
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor in goroutine 1
	go.opentelemetry.io/otel/sdk@v1.28.0/trace/batch_span_processor.go:115 +0x2e5
```

**Comment by alucarddelta** [comment]
Are we sure this was resolved? I've since loaded version 1.45.x to 1.48.0 and I get the same error when I try a valid body template.  Invalid body templates returns an error log, but does not crash the application. 
Sample of the error
```
2024-08-16T06:50:35Z	ERROR	failed to send audit to webhook	{"server": "grpc", "sink": "templates", "error": "invalid JSON: {a\n  \"type\": \"flag\",\n  \"action\": \"updated\",\n  \"metadata\": \"{\"actor\":{\"authentication\":\"oidc\",\"ip\":\"172.18.251.37\",\"email\":\"test@test.com\",\"name\":\"admin test\"}}\",\n  \"payload\": {\"description\":\"\",\"enabled\":true,\"key\":\"test_default_bool_1\",\"name\":\"test_default_bool_1\",\"namespace_key\":\"default\"}\n}\n"}
2024-08-16T06:50:35Z	ERROR	failed to send audits to sink	{"server": "grpc", "sink": "templates", "error": "1 error occurred:\n\t* invalid JSON: {a\n  \"type\": \"flag\",\n  \"action\": \"updated\",\n  \"metadata\": \"{\"actor\":{\"authentication\":\"oidc\",\"ip\":\"172.18.251.37\",\"email\":\"test@test.com\",\"name\":\"admin test\"}}\",\n  \"payload\": {\"description\":\"\",\"enabled\":true,\"key\":\"test_default_bool_1\",\"name\":\"test_default_bool_1\",\"namespace_key\":\"default\"}\n}\n\n\n"}
```

**Comment by erka** [comment]
Hey @alucarddelta

Thank you for raising this. You are right it isn't fully fixed. I will take a look on it today.

**Comment by GeorgeMac** [comment]
Cheers for jumping on this @erka 🙏

**Comment by GeorgeMac** [comment]
Hey @alucarddelta , @erka got a fix in and we just released `v1.48.1`.

Please let us know if the issues still persists after you upgrade to this version 🙏

**Comment by alucarddelta** [comment]
I have confirmed in `1.48.1` that audit webhooks are now working as expected.

Thank you for your quick response!
